# Generated by Django 4.1.7 on 2023-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_album_updated_at_artist_updated_at_song_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="song",
            name="release_date",
            field=models.DateTimeField(),
        ),
    ]
