version: "3.9"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
      - celery
  db:
    image: postgres
    environment:
      POSTGRES_DB: itunes_api_wrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./db:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
  redis:
    image: "redis"
    ports:
    - "6381:6379"
  celery:
    build: .
    command: celery -A itunes-api-wrapper worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=itunes-api-wrapper.settings
      - CELERY_BROKER_URL=redis://redis:6380
      - CELERY_RESULT_BACKEND=redis://redis:6380
